"""DOCX Generator for Business Plans"""

from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement
from datetime import datetime
import os
import re
import logging
from pathlib import Path

logger = logging.getLogger(__name__)

# Use /tmp for exports in Vercel (writable), or local exports directory for development
# Vercel serverless functions have a read-only filesystem except for /tmp
# Vercel automatically sets VERCEL=1 environment variable
def get_exports_dir():
    """Get the exports directory path, using /tmp in Vercel"""
    if os.environ.get("VERCEL") or os.environ.get("VERCEL_ENV"):
        return Path("/tmp/exports")
    else:
        BACKEND_DIR = Path(__file__).parent.parent
        return BACKEND_DIR / "exports"

# Create exports directory lazily (only when needed, not at import time)
def ensure_exports_dir():
    """Ensure exports directory exists"""
    exports_dir = get_exports_dir()
    try:
        exports_dir.mkdir(exist_ok=True, parents=True)
    except (OSError, PermissionError):
        # If we can't create the directory, try /tmp as fallback
        exports_dir = Path("/tmp/exports")
        exports_dir.mkdir(exist_ok=True, parents=True)
    return exports_dir

def generate_business_plan_docx(plan_data, sections_data, financial_data=None):
    """
    Generate a professional business plan DOCX.
    
    Args:
        plan_data: Plan metadata (name, purpose, etc.)
        sections_data: List of section objects with content
        financial_data: Financial model data (optional)
    
    Returns:
        str: Path to generated DOCX file
    """
    
    # Ensure exports directory exists and get path
    exports_dir = ensure_exports_dir()
    
    # Generate filename
    timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
    filename = f"business_plan_{plan_data.get('id', 'unknown')}_{timestamp}.docx"
    filepath = exports_dir / filename
    
    # Create document
    doc = Document()
    
    # Set document margins
    sections = doc.sections
    for section in sections:
        section.top_margin = Inches(1)
        section.bottom_margin = Inches(1)
        section.left_margin = Inches(1)
        section.right_margin = Inches(1)
    
    # Title Page
    title_para = doc.add_paragraph()
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title_run = title_para.add_run(plan_data.get('name', 'Business Plan'))
    title_run.font.size = Pt(28)
    title_run.font.color.rgb = RGBColor(0, 22, 57)  # #001639
    title_run.bold = True
    
    doc.add_paragraph()  # Spacing
    
    subtitle_para = doc.add_paragraph()
    subtitle_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    subtitle_run = subtitle_para.add_run(f"{datetime.utcnow().strftime('%B %d, %Y')}\nGenerated by Strattio")
    subtitle_run.font.size = Pt(12)
    subtitle_run.font.color.rgb = RGBColor(107, 114, 128)
    
    # Page break
    doc.add_page_break()
    
    # Table of Contents
    toc_heading = doc.add_heading('Table of Contents', level=1)
    toc_heading.alignment = WD_ALIGN_PARAGRAPH.LEFT
    
    # Sort sections by order_index
    sorted_sections = sorted(sections_data, key=lambda x: x.get('order_index', 999))
    
    for idx, section in enumerate(sorted_sections):
        toc_para = doc.add_paragraph(f"{idx + 1}. {section.get('title', 'Section')}")
        toc_para.style = 'List Number'
    
    doc.add_page_break()
    
    # Sections
    for idx, section in enumerate(sorted_sections):
        # Section heading
        heading = doc.add_heading(f"{idx + 1}. {section.get('title', 'Section')}", level=1)
        
        # Section content
        content = section.get('content', '')
        
        if not content or content.strip() == "":
            content = f"[{section.get('title')} content to be added]"
        
        # Convert HTML to plain text and format
        # Remove HTML tags
        content = re.sub(r'<[^>]+>', '', content)
        # Convert markdown-style formatting
        content = re.sub(r'\*\*([^*]+)\*\*', r'\1', content)  # Remove bold markers
        content = re.sub(r'\*([^*]+)\*', r'\1', content)  # Remove italic markers
        
        # Split into paragraphs
        paragraphs = content.split('\n\n')
        if not paragraphs:
            paragraphs = content.split('\n')
        
        for para_text in paragraphs:
            if para_text.strip():
                para = doc.add_paragraph(para_text.strip())
                para.paragraph_format.space_after = Pt(12)
        
        # Add spacing after section
        doc.add_paragraph()
    
    # Financial Summary (if available)
    if financial_data and financial_data.get('data'):
        doc.add_page_break()
        fin_heading = doc.add_heading('Financial Summary', level=1)
        
        fin_data = financial_data['data']
        
        # KPIs
        if 'kpis' in fin_data:
            kpis = fin_data['kpis']
            kpi_heading = doc.add_heading('Key Performance Indicators (Year 1)', level=2)
            kpi_text = f"Gross Margin: {kpis.get('gross_margin_percent', 0):.1f}%\n"
            kpi_text += f"Net Margin: {kpis.get('net_margin_percent', 0):.1f}%\n"
            kpi_text += f"ROI: {kpis.get('roi_year1_percent', 0):.1f}%"
            doc.add_paragraph(kpi_text)
        
        # P&L Table
        if 'pnl_annual' in fin_data:
            pnl_heading = doc.add_heading('5-Year Financial Projections', level=2)
            
            pnl = fin_data['pnl_annual']
            
            # Create table
            table = doc.add_table(rows=1, cols=6)
            table.style = 'Light Grid Accent 1'
            
            # Header row
            header_cells = table.rows[0].cells
            header_cells[0].text = 'Metric'
            header_cells[1].text = 'Year 1'
            header_cells[2].text = 'Year 2'
            header_cells[3].text = 'Year 3'
            header_cells[4].text = 'Year 4'
            header_cells[5].text = 'Year 5'
            
            # Make header bold
            for cell in header_cells:
                for paragraph in cell.paragraphs:
                    for run in paragraph.runs:
                        run.bold = True
            
            # Revenue row
            row = table.add_row()
            row.cells[0].text = 'Revenue (£)'
            for i, year in enumerate(pnl[:5], 1):
                row.cells[i].text = f"£{year.get('revenue', 0):,.0f}"
            
            # Gross Profit row
            row = table.add_row()
            row.cells[0].text = 'Gross Profit (£)'
            for i, year in enumerate(pnl[:5], 1):
                row.cells[i].text = f"£{year.get('gross_profit', 0):,.0f}"
            
            # Net Profit row
            row = table.add_row()
            row.cells[0].text = 'Net Profit (£)'
            for i, year in enumerate(pnl[:5], 1):
                row.cells[i].text = f"£{year.get('net_profit', 0):,.0f}"
    
    # Save document
    doc.save(str(filepath))
    
    logger.info(f"Generated DOCX: {filepath}")
    return str(filepath)
