"""PDF Generator for Business Plans with Template Support"""

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib import colors
from datetime import datetime
import os
from pathlib import Path
import sys
sys.path.append('/app/backend')
from agents.templates import TemplateFactory

# Create exports directory
EXPORTS_DIR = Path("/app/backend/exports")
EXPORTS_DIR.mkdir(exist_ok=True)

def generate_business_plan_pdf(plan_data, sections_data, financial_data=None):
    """
    Generate a professional business plan PDF.
    
    Args:
        plan_data: Plan metadata (name, purpose, etc.)
        sections_data: List of section objects with content
        financial_data: Financial model data (optional)
    
    Returns:
        str: Path to generated PDF file
    """
    
    # Generate filename
    timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
    filename = f"business_plan_{plan_data.get('id', 'unknown')}_{timestamp}.pdf"
    filepath = EXPORTS_DIR / filename
    
    # Create PDF document
    doc = SimpleDocTemplate(
        str(filepath),
        pagesize=A4,
        rightMargin=72,
        leftMargin=72,
        topMargin=72,
        bottomMargin=72
    )
    
    # Container for PDF elements
    story = []
    
    # Styles
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#1A85FF'),
        spaceAfter=30,
        alignment=TA_CENTER
    )
    
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=16,
        textColor=colors.HexColor('#2D3748'),
        spaceAfter=12,
        spaceBefore=20
    )
    
    body_style = ParagraphStyle(
        'CustomBody',
        parent=styles['Normal'],
        fontSize=11,
        leading=16,
        alignment=TA_LEFT,
        spaceAfter=12
    )
    
    # Get plan purpose and template info
    plan_purpose = plan_data.get('plan_purpose', 'generic')
    template_config = TemplateFactory.get_template(plan_purpose)
    
    # Title Page
    story.append(Spacer(1, 2*inch))
    story.append(Paragraph(plan_data.get('name', 'Business Plan'), title_style))
    story.append(Spacer(1, 0.3*inch))
    
    # Add plan type subtitle
    subtitle_text = f"{template_config.template_name}<br/>{datetime.utcnow().strftime('%B %d, %Y')}<br/>Generated by Strattio"
    story.append(Paragraph(
        subtitle_text,
        ParagraphStyle('SubTitle', parent=styles['Normal'], fontSize=12, alignment=TA_CENTER, textColor=colors.HexColor('#6B7A91'))
    ))
    story.append(PageBreak())
    
    # Table of Contents
    story.append(Paragraph("Table of Contents", heading_style))
    story.append(Spacer(1, 0.1*inch))
    
    # Sort sections by order_index for proper TOC
    sorted_sections = sorted(sections_data, key=lambda x: x.get('order_index', 999))
    
    for idx, section in enumerate(sorted_sections):
        toc_item = f"{idx + 1}. {section.get('title', 'Section')}"
        story.append(Paragraph(toc_item, body_style))
    
    story.append(PageBreak())
    
    # Sections (already sorted)
    for idx, section in enumerate(sorted_sections):
        # Section heading
        section_title = f"{idx + 1}. {section.get('title', 'Section')}"
        story.append(Paragraph(section_title, heading_style))
        
        # Section content
        content = section.get('content', '')
        
        # Handle empty or error sections
        if not content or content.strip() == "":
            content = f"[{section.get('title')} content to be added]"
        
        # Clean up content for PDF
        content = content.replace('\n', '<br/>')
        
        # Split into paragraphs
        paragraphs = content.split('<br/><br/>')
        for para in paragraphs:
            if para.strip():
                story.append(Paragraph(para, body_style))
                story.append(Spacer(1, 6))
        
        # Add some space after section
        story.append(Spacer(1, 0.3*inch))
    
    # Financial Summary (if available)
    if financial_data and financial_data.get('data'):
        story.append(PageBreak())
        story.append(Paragraph("Financial Summary", heading_style))
        
        fin_data = financial_data['data']
        
        # KPIs
        if 'kpis' in fin_data:
            kpis = fin_data['kpis']
            story.append(Paragraph("<b>Key Performance Indicators (Year 1)</b>", body_style))
            kpi_text = f"""
            • Gross Margin: {kpis.get('gross_margin_percent', 0):.1f}%<br/>
            • Net Margin: {kpis.get('net_margin_percent', 0):.1f}%<br/>
            • ROI: {kpis.get('roi_year1_percent', 0):.1f}%
            """
            story.append(Paragraph(kpi_text, body_style))
            story.append(Spacer(1, 0.2*inch))
        
        # P&L Table
        if 'pnl_annual' in fin_data:
            story.append(Paragraph("<b>5-Year Financial Projections</b>", body_style))
            story.append(Spacer(1, 0.1*inch))
            
            pnl = fin_data['pnl_annual']
            
            # Build table data
            table_data = [
                ['Metric', 'Year 1', 'Year 2', 'Year 3', 'Year 4', 'Year 5']
            ]
            
            # Revenue row
            revenue_row = ['Revenue (£)'] + [f"£{year.get('revenue', 0):,.0f}" for year in pnl[:5]]
            table_data.append(revenue_row)
            
            # Gross Profit row
            gp_row = ['Gross Profit (£)'] + [f"£{year.get('gross_profit', 0):,.0f}" for year in pnl[:5]]
            table_data.append(gp_row)
            
            # Net Profit row
            np_row = ['Net Profit (£)'] + [f"£{year.get('net_profit', 0):,.0f}" for year in pnl[:5]]
            table_data.append(np_row)
            
            # Create table
            table = Table(table_data, colWidths=[2*inch, 1*inch, 1*inch, 1*inch, 1*inch, 1*inch])
            table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1A85FF')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 10),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
                ('GRID', (0, 0), (-1, -1), 1, colors.grey),
                ('FONTNAME', (0, 1), (0, -1), 'Helvetica-Bold'),
            ]))
            story.append(table)
    
    # Build PDF
    doc.build(story)
    
    return str(filepath)
